### ISSUE TITLE
Extra icon for each tabs and icon missing for contact search result.

### ISSUE THREAD

**Issue by tapashdatta** [civicrm/org.civicrm.shoreditch#376]
<img width="263" alt="Screenshot 2019-03-16 at 06 16 32" src="https://user-images.githubusercontent.com/5366545/54471600-64f4e580-47b3-11e9-91fd-f908e9e2ea32.png">
each tab showing an extra icon next to it.

<img width="124" alt="Screenshot 2019-03-17 at 10 50 43" src="https://user-images.githubusercontent.com/5366545/54562353-c046f380-49be-11e9-8bc2-d522c5b38f6e.png">
Icon Missing for search result.

<img width="1429" alt="Screenshot 2019-03-19 at 17 05 49" src="https://user-images.githubusercontent.com/5366545/54626667-8979e780-4a69-11e9-8a04-23487bc20fa3.png">
"New mailing" buttons color missing

**Comment by rekaeps** [comment]
I noticed this, too. Running latest version of CiviCRM and Shoreditch.

**Comment by colemanw** [comment]
I believe this was fixed by https://github.com/civicrm/org.civicrm.shoreditch/issues/340

**Comment by tapashdatta** [comment]
Thanks. I think it's still not fixed yet. I have Updated CSS, uninstall, and reinstalled numerous from github but still have additional icons appearing. Clearing cache also didnt help. What could be the reason please?

**Comment by tapashdatta** [comment]
I have tested on my production site running CiviCRM 5.11.0, PHP7.1, Drupal 7.x. Also have tested on a clean install CiviCRM 5.12.3, PHP7.1, Drupal 7.x

**Comment by AkA84** [comment]
hi @tapashdatta , we haven't released #340 yet (see the [comparison](https://github.com/civicrm/org.civicrm.shoreditch/compare/v0.1-alpha31...master) between the latest release and current `master`).

If you want to use the fix before we release `v0.1-alpha32`, please pull `master` and follow the instructions on https://github.com/civicrm/org.civicrm.shoreditch#installation-gitcli, where it says

> If you [...] want the very latest (but untested) version of the theme on your site [...]
