### ISSUE TITLE
Critical: Cannot Edit Existing Navigation Menu

### ISSUE THREAD

**Issue by sleewok** [civicrm/org.civicrm.shoreditch#425]
When trying to customize the navigation menu you cannot right click and edit existing items. 

This is pretty important loss of functionality.

T**o fix, the z-index needs to be set to 1 for:**

.jstree-contextmenu.vakata-context

**Comment by jamienovick** [comment]
Please let us know which version of Shoreditch and CiviCRM and base CMS. Thanks

**Comment by sleewok** [comment]
CiviCRM version: 5.18.1
Shoreditch version: Clone of master on github

**Comment by sleewok** [comment]
This is sort of a big deal. Any idea when it will be fixed?

**Comment by tapashdatta** [comment]
I am still having this issue. no context menu loading for navigation. I am on 5.20.3, drupal 7.x
I can see some js error in chrome console

```
js_YL4xAxlPEepJ_TGj59RUxAQcWVrjjCXe9U1tKFAQk6c.js:23 Uncaught TypeError: $(...).afterResize is not a function
    at stickymenu (js_YL4xAxlPEepJ_TGj59RUxAQcWVrjjCXe9U1tKFAQk6c.js:23)
    at HTMLDocument.<anonymous> (js_YL4xAxlPEepJ_TGj59RUxAQcWVrjjCXe9U1tKFAQk6c.js:108)
    at c (js_EebRuRXFlkaf356V0T2K_8cnUVfCKesNTxdvvPSEhCM.js:4)
    at Object.fireWith [as resolveWith] (js_EebRuRXFlkaf356V0T2K_8cnUVfCKesNTxdvvPSEhCM.js:4)
    at Function.ready (js_EebRuRXFlkaf356V0T2K_8cnUVfCKesNTxdvvPSEhCM.js:4)
    at HTMLDocument.q (js_EebRuRXFlkaf356V0T2K_8cnUVfCKesNTxdvvPSEhCM.js:4)
```

**Comment by sleewok** [comment]
Fixed: https://github.com/civicrm/org.civicrm.shoreditch/pull/430

**Comment by Fabian-SYSTOPIA** [comment]
We are still experiencing this issue in CiviCRM 5.29.1 & Shoreditch 0.1-alpha35. We are using the Shoreditch CiviAdmin Companion Drupal theme 1.0.

**Comment by tschuettler** [comment]
> 
> 
> We are still experiencing this issue in CiviCRM 5.29.1 & Shoreditch 0.1-alpha35. We are using the Shoreditch CiviAdmin Companion Drupal theme 1.0.

@Fabian-SYSTOPIA It looks like the fix went into 0.1.0-alpha.36 of Shoreditch

**Comment by Fabian-SYSTOPIA** [comment]
> > We are still experiencing this issue in CiviCRM 5.29.1 & Shoreditch 0.1-alpha35. We are using the Shoreditch CiviAdmin Companion Drupal theme 1.0.
> 
> @Fabian-SYSTOPIA It looks like the fix went into 0.1.0-alpha.36 of Shoreditch

Thanks, I will update soon and give feedback here.
